[tool.poetry]
name = "cschwabpy"
version = "0.1.0"
description = ""
authors = ["Tony Wang <ivytony@gmail.com>"]
readme = "README.md"
packages = [{include = "cschwab"}]

[tool.poetry.dependencies]
python = "^3.11.5"
httpx-auth = "^0.22.0"
httpx = "^0.27.0"
pytest = "^8.2.1"
pre-commit = "^3.7.1"
pytest-asyncio = "^0.23.7"
pydantic = "^2.7.3"
prompt-toolkit = "^3.0.45"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
